import { capitalizeEveryFirstLetter } from './general'

const revealFormElement = (target, toggleType, e) => {
   const formNodes = e.target.closest('form').querySelectorAll('fieldset');
   formNodes.forEach(node => {
      const text = node.querySelector('span').textContent;

      if (text == capitalizeEveryFirstLetter(target)) {
         switch (toggleType) {
         case 'remove': return node.classList.remove('visibility-none');
         case 'add'   : return node.classList.add('visibility-none');
         }
      }
   })
}

export function formStructure () {
   const form = {
      header: 'Add Feeding',
      inputs: [
      // Baby Name
      {
         name:'first_name',
         type: 'input_radio',
         radio: [
            'Liam',
            'Sophia',
         ]
      },
      // Events
      {
         name:'event_type',
         type:'input_radio',
         radio: [
            'Bath',
            'Diaper',
            'Feeding',
            'Growth',
            'Medication',
            'Night Check',
            'Pumping',
            'Temperature',
            'Tummy Time',
         ],
         className:'event-type',
         events: {
            onClick:[
            (e) => {
               revealFormElement('feeding_type',               'add', e);
               revealFormElement('breast',                     'add', e);
               revealFormElement('bottle',                     'add', e);
               revealFormElement('bath_post_care_oil',         'add', e);
               revealFormElement('bath_post_care_lotion',      'add', e);
               revealFormElement('diaper_type',                'add', e);
               revealFormElement('growth_height',              'add', e);
               revealFormElement('growth_height_unit',         'add', e);
               revealFormElement('growth_weight',              'add', e);
               revealFormElement('growth_weight_unit',         'add', e);
               revealFormElement('medication_name',            'add', e);
               revealFormElement('medication_dosage',          'add', e);
               revealFormElement('medication_dosage_unit',     'add', e);
               revealFormElement('night_check_frequency',      'add', e);
               revealFormElement('night_check_frequency_unit', 'add', e);
               revealFormElement('pumping_amount_(oz)',        'add', e);
               revealFormElement('pumping_breast',             'add', e);
               revealFormElement('temperature_degree_f',       'add', e);
               revealFormElement('tummy_time_duration',        'add', e);
               revealFormElement('tummy_time_duration_units',  'add', e);
   
               switch(e.target.value) {
                  case 'Feeding':
                  revealFormElement('feeding_type', 'remove', e);
                  break;
                  case 'Bath'   :
                  revealFormElement('bath_post_care_oil',    'remove', e);
                  revealFormElement('bath_post_care_lotion', 'remove', e);
                  break;
                  case 'Diaper' :
                  revealFormElement('diaper_type', 'remove', e);
                  break;
                  case 'Growth' :
                  revealFormElement('growth_height',      'remove', e);
                  revealFormElement('growth_height_unit', 'remove', e);
                  revealFormElement('growth_weight',      'remove', e);
                  revealFormElement('growth_weight_unit', 'remove', e);
                  break;
                  case 'Medication':
                  revealFormElement('medication_name',        'remove', e);
                  revealFormElement('medication_dosage',      'remove', e);
                  revealFormElement('medication_dosage_unit', 'remove', e);
                  break;
                  case 'Night Check':
                  revealFormElement('night_check_frequency',      'remove', e);
                  revealFormElement('night_check_frequency_unit', 'remove', e);
                  break;
                  case 'Pumping'    :
                  revealFormElement('pumping_amount_(oz)', 'remove', e);
                  revealFormElement('pumping_breast',      'remove', e);
                  break;
                  case 'Temperature':
                  revealFormElement('temperature_degree_f', 'remove', e);
                  break;
                  case 'Tummy Time':
                  revealFormElement('tummy_time_duration',       'remove', e);
                  revealFormElement('tummy_time_duration_units', 'remove', e);
                  break;
               }
            }
            ]
         }
      },
      {
         name: 'feeding_type',
         type: 'input_radio',
         radio: ['Bottle', 'Breast'],
         className: "visibility visibility-none",
         events: {
            onClick:[
            (e) => {
               (e.target.value === 'Breast')
                  ? revealFormElement('breast', 'remove', e)
                  : revealFormElement('breast', 'add',    e);
            },
            (e) => {
               (e.target.value === 'Bottle')
                  ? revealFormElement('bottle', 'remove', e)
                  : revealFormElement('bottle', 'add',    e);
            },
            ]
         },
      },
      // ! ====== AUX Items ====== ! //
      // ! Bath
      {
         name: 'bath_post_care_oil',
         type: 'input_checkbox',
         className: "visibility visibility-none",
         checked: false,
      },
      {
         name: 'bath_post_care_lotion',
         type: 'input_checkbox',
         className: "visibility visibility-none",
         checked: false,
      },
      // ! Diaper
      {
         name: 'diaper_type',
         type: 'input_radio',
         radio: ['Pee', 'Poop', 'Blow-out'],
         className: "visibility visibility-none",
      },
      // ! Feeding
      {
         name: 'breast',
         type: 'input_radio',
         radio: ['Left', 'Right'],
         className: "visibility visibility-none"
      },
      {
         name: 'bottle',
         type: 'input_radio',
         radio: Array.from({ length:16 }, (_, i) => i + 1 + ' oz'),
         className: "visibility visibility-none"
      },
      // ! Growth
      {
         name: 'growth_height',
         type: 'input_text',
         className: "visibility visibility-none",
         inputType: 'number',
         step: 1,
         min: 0,
         max: 100,
      },
      {
         name: 'growth_height_unit',
         type: 'input_radio',
         className: "visibility visibility-none",
         radio: ['inches', 'centimeter'],
      },
      {
         name: 'growth_weight',
         type: 'input_text',
         className: "visibility visibility-none",
         inputType: 'number',
         step: 1,
         min: 0,
         max: 200,
      },
      {
         name: 'growth_weight_unit',
         type: 'input_radio',
         className: "visibility visibility-none",
         radio: ['oz', 'lbs']
      },
      // ! Medication
      {
         name: 'medication_name',
         type: 'input_text',
         className: "visibility visibility-none",
         inputType: 'text',
      },
      {
         name: 'medication_dosage',
         type: 'input_text',
         className: "visibility visibility-none",
         inputType: 'number',
         step: .01,
         min: 0,
         max: 200,
      },
      {
         name: 'medication_dosage_unit',
         type: 'input_radio',
         className: "visibility visibility-none",
         radio: ['Pill', 'oz', 'Other']
      },
      // ! Night check
      {
         name: 'night_check_frequency',
         type: 'input_text',
         className: "visibility visibility-none",
         inputType: 'number',
         step: 1,
         min: 0,
         max: 100,
      },
      {
         name: 'night_check_frequency_unit',
         type: 'input_radio',
         className: "visibility visibility-none",
         radio: ['Hour','Minute']
      },
      // ! Pumping
      {
         name: 'pumping_amount_(oz)',
         type: 'input_text',
         className: "visibility visibility-none",
         inputType: 'number',
         step: .01,
         min: 0,
         max: 100,
      },
      {
         name: 'pumping_breast',
         type: 'input_radio',
         radio: ['Left', 'Right'],
         className: "visibility visibility-none"
      },
      // ! Temperature
      {
         name: 'temperature_degree_f',
         type: 'input_text',
         className: "visibility visibility-none",
         inputType: 'number',
         step: 1,
         min: 0,
         max: 100,
      },
      // ! Tummy Time
      {
         name: 'tummy_time_duration',
         type: 'input_text',
         className: "visibility visibility-none",
         inputType: 'number',
         step: 1,
         min: 0,
         max: 100,
      },
      {
         name: 'tummy_time_duration_units',
         type: 'input_radio',
         className: "visibility visibility-none",
         radio: [
            'Minutes', 'Hours'
         ]
      },
      {
         name:'notes',
         type:'textarea',
      }
      ]
   }
   form.inputs.map(input => input.key = crypto.randomUUID());
   return form;
}


export function jsonFillerFile() {
return [
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 70,
     "baby_id": 2,
     "event_type": "PUMPING",
     "start_on": "2025-02-10T23:35:00",
     "end_on": "2025-02-10T23:55:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 69,
     "baby_id": 1,
     "event_type": "NIGHT_CHECK",
     "start_on": "2025-02-10T23:10:00",
     "end_on": "2025-02-10T23:30:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 68,
     "baby_id": 2,
     "event_type": "MEDICATION",
     "start_on": "2025-02-10T22:45:00",
     "end_on": "2025-02-10T23:05:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 67,
     "baby_id": 1,
     "event_type": "GROWTH",
     "start_on": "2025-02-10T22:20:00",
     "end_on": "2025-02-10T22:40:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 66,
     "baby_id": 2,
     "event_type": "DIAPER",
     "start_on": "2025-02-10T22:05:00",
     "end_on": "2025-02-10T22:15:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 65,
     "baby_id": 1,
     "event_type": "FEEDING",
     "start_on": "2025-02-10T21:40:00",
     "end_on": "2025-02-10T22:00:00",
     "amount": 145.5,
     "feeding_type": "FORMULA",
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 64,
     "baby_id": 2,
     "event_type": "BATH",
     "start_on": "2025-02-10T21:10:00",
     "end_on": "2025-02-10T21:35:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 63,
     "baby_id": 1,
     "event_type": "TUMMY_TIME",
     "start_on": "2025-02-10T20:40:00",
     "end_on": "2025-02-10T21:00:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 62,
     "baby_id": 2,
     "event_type": "TEMPERATURE",
     "start_on": "2025-02-10T20:10:00",
     "end_on": "2025-02-10T20:30:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 61,
     "baby_id": 1,
     "event_type": "PUMPING",
     "start_on": "2025-02-10T19:40:00",
     "end_on": "2025-02-10T20:00:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 60,
     "baby_id": 2,
     "event_type": "NIGHT_CHECK",
     "start_on": "2025-02-10T19:10:00",
     "end_on": "2025-02-10T19:30:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 59,
     "baby_id": 1,
     "event_type": "MEDICATION",
     "start_on": "2025-02-10T18:40:00",
     "end_on": "2025-02-10T19:00:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 58,
     "baby_id": 2,
     "event_type": "GROWTH",
     "start_on": "2025-02-10T18:15:00",
     "end_on": "2025-02-10T18:35:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 57,
     "baby_id": 1,
     "event_type": "DIAPER",
     "start_on": "2025-02-10T18:00:00",
     "end_on": "2025-02-10T18:10:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 56,
     "baby_id": 2,
     "event_type": "FEEDING",
     "start_on": "2025-02-10T17:35:00",
     "end_on": "2025-02-10T17:55:00",
     "amount": 115,
     "feeding_type": "BREAST",
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 55,
     "baby_id": 1,
     "event_type": "BATH",
     "start_on": "2025-02-10T17:05:00",
     "end_on": "2025-02-10T17:30:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 54,
     "baby_id": 2,
     "event_type": "TUMMY_TIME",
     "start_on": "2025-02-10T16:40:00",
     "end_on": "2025-02-10T17:00:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 53,
     "baby_id": 1,
     "event_type": "TEMPERATURE",
     "start_on": "2025-02-10T16:10:00",
     "end_on": "2025-02-10T16:30:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 52,
     "baby_id": 2,
     "event_type": "PUMPING",
     "start_on": "2025-02-10T15:40:00",
     "end_on": "2025-02-10T16:00:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 51,
     "baby_id": 1,
     "event_type": "NIGHT_CHECK",
     "start_on": "2025-02-10T15:10:00",
     "end_on": "2025-02-10T15:30:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 50,
     "baby_id": 2,
     "event_type": "MEDICATION",
     "start_on": "2025-02-10T14:40:00",
     "end_on": "2025-02-10T15:00:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 49,
     "baby_id": 1,
     "event_type": "GROWTH",
     "start_on": "2025-02-10T14:15:00",
     "end_on": "2025-02-10T14:35:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 48,
     "baby_id": 2,
     "event_type": "DIAPER",
     "start_on": "2025-02-10T14:00:00",
     "end_on": "2025-02-10T14:10:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 47,
     "baby_id": 1,
     "event_type": "FEEDING",
     "start_on": "2025-02-10T13:35:00",
     "end_on": "2025-02-10T13:55:00",
     "amount": 90,
     "feeding_type": "SOLID",
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 46,
     "baby_id": 2,
     "event_type": "BATH",
     "start_on": "2025-02-10T13:05:00",
     "end_on": "2025-02-10T13:30:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 45,
     "baby_id": 1,
     "event_type": "TUMMY_TIME",
     "start_on": "2025-02-10T12:40:00",
     "end_on": "2025-02-10T13:00:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 44,
     "baby_id": 2,
     "event_type": "TEMPERATURE",
     "start_on": "2025-02-10T12:10:00",
     "end_on": "2025-02-10T12:30:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 43,
     "baby_id": 1,
     "event_type": "PUMPING",
     "start_on": "2025-02-10T11:40:00",
     "end_on": "2025-02-10T12:00:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 42,
     "baby_id": 2,
     "event_type": "NIGHT_CHECK",
     "start_on": "2025-02-10T11:10:00",
     "end_on": "2025-02-10T11:30:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 41,
     "baby_id": 1,
     "event_type": "MEDICATION",
     "start_on": "2025-02-10T10:40:00",
     "end_on": "2025-02-10T11:00:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 40,
     "baby_id": 2,
     "event_type": "GROWTH",
     "start_on": "2025-02-10T10:15:00",
     "end_on": "2025-02-10T10:35:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 39,
     "baby_id": 1,
     "event_type": "DIAPER",
     "start_on": "2025-02-10T10:00:00",
     "end_on": "2025-02-10T10:10:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 38,
     "baby_id": 2,
     "event_type": "FEEDING",
     "start_on": "2025-02-10T09:30:00",
     "end_on": "2025-02-10T09:55:00",
     "amount": 130,
     "feeding_type": "FORMULA",
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 37,
     "baby_id": 1,
     "event_type": "BATH",
     "start_on": "2025-02-10T09:00:00",
     "end_on": "2025-02-10T09:25:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 36,
     "baby_id": 2,
     "event_type": "TUMMY_TIME",
     "start_on": "2025-02-10T08:25:00",
     "end_on": "2025-02-10T08:45:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 35,
     "baby_id": 1,
     "event_type": "TEMPERATURE",
     "start_on": "2025-02-10T08:00:00",
     "end_on": "2025-02-10T08:20:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 34,
     "baby_id": 2,
     "event_type": "PUMPING",
     "start_on": "2025-02-09T23:35:00",
     "end_on": "2025-02-09T23:55:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 33,
     "baby_id": 1,
     "event_type": "NIGHT_CHECK",
     "start_on": "2025-02-09T23:10:00",
     "end_on": "2025-02-09T23:30:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 32,
     "baby_id": 2,
     "event_type": "MEDICATION",
     "start_on": "2025-02-09T22:45:00",
     "end_on": "2025-02-09T23:05:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 31,
     "baby_id": 1,
     "event_type": "GROWTH",
     "start_on": "2025-02-09T22:20:00",
     "end_on": "2025-02-09T22:40:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 30,
     "baby_id": 2,
     "event_type": "DIAPER",
     "start_on": "2025-02-09T22:05:00",
     "end_on": "2025-02-09T22:15:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 29,
     "baby_id": 1,
     "event_type": "FEEDING",
     "start_on": "2025-02-09T21:40:00",
     "end_on": "2025-02-09T22:00:00",
     "amount": 100,
     "feeding_type": "BREAST",
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 28,
     "baby_id": 2,
     "event_type": "BATH",
     "start_on": "2025-02-09T21:10:00",
     "end_on": "2025-02-09T21:35:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 27,
     "baby_id": 1,
     "event_type": "TUMMY_TIME",
     "start_on": "2025-02-09T20:40:00",
     "end_on": "2025-02-09T21:00:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 26,
     "baby_id": 2,
     "event_type": "TEMPERATURE",
     "start_on": "2025-02-09T20:10:00",
     "end_on": "2025-02-09T20:30:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 25,
     "baby_id": 1,
     "event_type": "PUMPING",
     "start_on": "2025-02-09T19:40:00",
     "end_on": "2025-02-09T20:00:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 24,
     "baby_id": 2,
     "event_type": "NIGHT_CHECK",
     "start_on": "2025-02-09T19:10:00",
     "end_on": "2025-02-09T19:30:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 23,
     "baby_id": 1,
     "event_type": "MEDICATION",
     "start_on": "2025-02-09T18:40:00",
     "end_on": "2025-02-09T19:00:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 22,
     "baby_id": 2,
     "event_type": "GROWTH",
     "start_on": "2025-02-09T18:15:00",
     "end_on": "2025-02-09T18:35:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 21,
     "baby_id": 1,
     "event_type": "DIAPER",
     "start_on": "2025-02-09T18:00:00",
     "end_on": "2025-02-09T18:10:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 20,
     "baby_id": 2,
     "event_type": "FEEDING",
     "start_on": "2025-02-09T17:30:00",
     "end_on": "2025-02-09T17:55:00",
     "amount": 80,
     "feeding_type": "SOLID",
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 19,
     "baby_id": 1,
     "event_type": "BATH",
     "start_on": "2025-02-09T17:00:00",
     "end_on": "2025-02-09T17:25:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 18,
     "baby_id": 2,
     "event_type": "TUMMY_TIME",
     "start_on": "2025-02-09T16:30:00",
     "end_on": "2025-02-09T16:50:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 17,
     "baby_id": 1,
     "event_type": "TEMPERATURE",
     "start_on": "2025-02-09T16:00:00",
     "end_on": "2025-02-09T16:20:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 16,
     "baby_id": 2,
     "event_type": "PUMPING",
     "start_on": "2025-02-09T15:30:00",
     "end_on": "2025-02-09T15:55:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 15,
     "baby_id": 1,
     "event_type": "NIGHT_CHECK",
     "start_on": "2025-02-09T15:00:00",
     "end_on": "2025-02-09T15:20:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 14,
     "baby_id": 2,
     "event_type": "MEDICATION",
     "start_on": "2025-02-09T14:30:00",
     "end_on": "2025-02-09T14:50:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 13,
     "baby_id": 1,
     "event_type": "GROWTH",
     "start_on": "2025-02-09T14:00:00",
     "end_on": "2025-02-09T14:15:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 12,
     "baby_id": 2,
     "event_type": "DIAPER",
     "start_on": "2025-02-09T13:30:00",
     "end_on": "2025-02-09T13:50:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 11,
     "baby_id": 1,
     "event_type": "FEEDING",
     "start_on": "2025-02-09T13:00:00",
     "end_on": "2025-02-09T13:20:00",
     "amount": 150.5,
     "feeding_type": "FORMULA",
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 10,
     "baby_id": 2,
     "event_type": "BATH",
     "start_on": "2025-02-09T12:30:00",
     "end_on": "2025-02-09T12:55:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 9,
     "baby_id": 1,
     "event_type": "TUMMY_TIME",
     "start_on": "2025-02-09T12:05:00",
     "end_on": "2025-02-09T12:25:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 8,
     "baby_id": 2,
     "event_type": "TEMPERATURE",
     "start_on": "2025-02-09T11:40:00",
     "end_on": "2025-02-09T12:00:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 7,
     "baby_id": 1,
     "event_type": "PUMPING",
     "start_on": "2025-02-09T11:00:00",
     "end_on": "2025-02-09T11:25:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 6,
     "baby_id": 2,
     "event_type": "NIGHT_CHECK",
     "start_on": "2025-02-09T10:30:00",
     "end_on": "2025-02-09T10:50:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 5,
     "baby_id": 1,
     "event_type": "MEDICATION",
     "start_on": "2025-02-09T09:45:00",
     "end_on": "2025-02-09T10:05:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 4,
     "baby_id": 2,
     "event_type": "GROWTH",
     "start_on": "2025-02-09T09:15:00",
     "end_on": "2025-02-09T09:30:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 3,
     "baby_id": 1,
     "event_type": "DIAPER",
     "start_on": "2025-02-09T09:00:00",
     "end_on": "2025-02-09T09:10:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2023-09-20T00:00:00",
     "first_name": "Sophia",
     "last_name": "Williams",
     "gender": "FEMALE",
     "event_id": 2,
     "baby_id": 2,
     "event_type": "FEEDING",
     "start_on": "2025-02-09T08:30:00",
     "end_on": "2025-02-09T08:55:00",
     "amount": 120,
     "feeding_type": "BREAST",
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   },
   {
     "birthday": "2024-06-15T00:00:00",
     "first_name": "Liam",
     "last_name": "Johnson",
     "gender": "MALE",
     "event_id": 1,
     "baby_id": 1,
     "event_type": "BATH",
     "start_on": "2025-02-09T08:00:00",
     "end_on": "2025-02-09T08:25:00",
     "amount": null,
     "feeding_type": null,
     "note_id": null,
     "note": null,
     "color": null,
     "height": null,
     "weight": null,
     "name": null,
     "dosage": null
   }
 ]
}