export interface Event {
   key         : string,
   amount      : number,
   baby_id     : number,
   birthday    : string,
   color       : string,
   dosage      : number,
   end_on      : string,
   event_id    : number,
   event_type  : string,
   feeding_type: string,
   first_name  : string,
   gender      : string,
   height      : number,
   last_name   : string,
   name        : string,
   note        : string,
   note_id     : number,
   start_on    : string,
   weight      : number,
}